# Generated by Django 4.0.3 on 2022-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birthday',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
