# Generated by Django 4.0.3 on 2022-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_events_remove_register_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='event',
            field=models.CharField(choices=[('Perform', 'Perform'), ('Dynatrace go', 'Dynatrace go'), ('Amplify', 'Amplify')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
