# Generated by Django 4.0.3 on 2022-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0004_register_gender_alter_register_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='event_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
